#!/bin/sh

cat << EOF > /root/profile.sh
export MYSQL_PORT_3306_TCP_ADDR=$MYSQL_PORT_3306_TCP_ADDR
export MYSQL_ENV_MYSQL_DATABASE=$MYSQL_ENV_MYSQL_DATABASE
export MYSQL_ENV_MYSQL_USER=$MYSQL_ENV_MYSQL_USER
export MYSQL_ENV_MYSQL_PASSWORD=$MYSQL_ENV_MYSQL_PASSWORD
EOF

chmod +x /root/profile.sh
